version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: evolution_postgres
    restart: always
    environment:
      POSTGRES_DB: evolution
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: evoapicloud/evolution-api:latest
    container_name: evolution_api
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SERVER_URL: http://103.93.129.104:8080
      AUTHENTICATION_TYPE: apikey
      AUTHENTICATION_API_KEY: LaundrySuperSecretKey123
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: postgresql
      DATABASE_CONNECTION_URI: postgresql://root:rootpassword@postgres:5432/evolution?schema=public
      DATABASE_SAVE_DATA_INSTANCE: "true"
      WEBHOOK_GLOBAL_ENABLED: "true"
      WEBHOOK_GLOBAL_URL: https://lmm.app.n8n.cloud/webhook/7efd4781-cf21-400d-b270-60b870b2d4d4
      WEBHOOK_GLOBAL_WEBHOOK_BY_EVENTS: "false"
      WEBHOOK_EVENTS_MESSAGES_UPSERT: "true"
      WEBHOOK_EVENTS_SEND_MESSAGE: "true"
      WEBHOOK_EVENTS_GROUPS_UPSERT: "true"
      WEBHOOK_EVENTS_CONNECTION_UPDATE: "false"

volumes:
  postgres_data:
