/**
 * Unit tests for the column model / seed check, plus a differential test that
 * the model parsed from REAL pg_dump output equals information_schema
 * (skipped unless LM_PG_ROLES_TEST=1 with the local cluster, see README).
 */
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, it } from 'node:test';
import { PR_MIGRATION_FILES } from './prMigrations';
import { CATALOG_QUERY, checkSeed, modelFromCatalog, modelFromSql, seedInserts, type TableModel } from './tableColumns';

const ROOT = join(__dirname, '..', '..');
const seed = readFileSync(join(ROOT, 'scripts/staging/seed.sql'), 'utf8');

/** Production-like schema WITHOUT app_settings.promos_data (the staging failure). */
const PROD_LIKE = `
CREATE TABLE public.outlets (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name text NOT NULL,
    city text,
    address_detail text,
    latitude double precision,
    longitude double precision,
    is_coming_soon boolean DEFAULT false
);
CREATE TABLE public.app_settings (
    id bigint NOT NULL,
    dynamic_services text,
    outlet_overrides jsonb,
    receipt_terms text
);
CREATE SEQUENCE public.app_settings_id_seq;
ALTER TABLE ONLY public.app_settings ALTER COLUMN id SET DEFAULT nextval('public.app_settings_id_seq'::regclass);
CREATE TABLE public.customers (phone text NOT NULL, name text, created_at timestamp with time zone DEFAULT now() NOT NULL);
CREATE TABLE public.customer_addresses (
    id bigint NOT NULL, customer_phone text NOT NULL, label_name text, full_address text,
    is_primary boolean DEFAULT false, latitude numeric, longitude numeric
);
ALTER TABLE public.customer_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME public.ca_id_seq START WITH 1 INCREMENT BY 1);
CREATE TABLE public.employees (id uuid DEFAULT gen_random_uuid() NOT NULL, name text, role text, outlet_id uuid, username text, password text);
ALTER TABLE ONLY public.customers ADD CONSTRAINT customers_pkey PRIMARY KEY (phone);
`;

const cols = (m: TableModel, t: string) => [...(m.get(t)?.values() || [])];

describe('column model from pg_dump text', () => {
  it('understands DEFAULT via later ALTER, identity, NOT NULL, named NOT NULL and ADD COLUMN in migrations', () => {
    const m = modelFromSql(
      PROD_LIKE,
      'CREATE TABLE public.t18 (a integer CONSTRAINT t18_a_not_null NOT NULL, b text, CONSTRAINT t18_b_nn NOT NULL b, g text GENERATED ALWAYS AS (b) STORED);',
      "alter table customers add column if not exists email text not null default '', add column verified_at timestamptz;\nalter table public.employees drop column password, alter column role set not null;"
    );
    const id = m.get('public.app_settings')!.get('id')!;
    assert.deepEqual([id.notNull, id.hasDefault], [true, true]);
    assert.equal(m.get('public.customer_addresses')!.get('id')!.identity, true);
    assert.equal(m.get('public.t18')!.get('a')!.notNull, true);
    assert.equal(m.get('public.t18')!.get('b')!.notNull, true);
    assert.equal(m.get('public.t18')!.get('g')!.generatedAlways, true);
    assert.equal(m.get('public.customers')!.get('email')!.hasDefault, true);
    assert.ok(m.get('public.customers')!.has('verified_at'));
    assert.ok(!m.get('public.employees')!.has('password'));
    assert.equal(m.get('public.employees')!.get('role')!.notNull, true);
    assert.equal(m.get('public.outlets')!.get('latitude')!.type, 'double precision');
  });

  it('the OLD seed line is caught: promos_data does not exist in a production-like schema', () => {
    const old = "insert into app_settings (id, dynamic_services, outlet_overrides, receipt_terms, promos_data)\nselect 1, '[]', '{}', 'x', '[]';";
    assert.deepEqual(checkSeed(modelFromSql(PROD_LIKE), seedInserts(old)), [{ line: 1, table: 'public.app_settings', problem: 'column "promos_data" does not exist' }]);
  });

  it('flags missing tables, required columns without default, generated columns and missing column lists', () => {
    const m = modelFromSql(PROD_LIKE, 'CREATE TABLE public.g (id int, v text GENERATED ALWAYS AS (id::text) STORED);');
    const issues = checkSeed(
      m,
      seedInserts("insert into customer_addresses (label_name) values ('x');\ninsert into nope (a) values (1);\ninsert into g (id, v) values (1, 'a');\ninsert into outlets values (1);")
    ).map((i) => `${i.line} ${i.problem}`);
    assert.deepEqual(issues, [
      '1 required column "customer_phone" (text, NOT NULL, no default) is not supplied',
      '2 table does not exist in the staging schema',
      '3 column "v" is GENERATED ALWAYS (cannot be inserted)',
      '4 INSERT without a column list (cannot be verified)'
    ]);
  });

  it('the current staging seed fits a production-like schema + PR migrations', () => {
    const migrations = PR_MIGRATION_FILES.map((f) => readFileSync(join(ROOT, 'supabase/migrations', f), 'utf8'));
    assert.deepEqual(checkSeed(modelFromSql(PROD_LIKE, ...migrations), seedInserts(seed)), []);
    assert.ok(!/promos_data/.test(seed.replace(/^--.*$/gm, '')));
  });
});

// ---- differential: parsed real pg_dump == information_schema ---------------
const enabled = process.env.LM_PG_ROLES_TEST === '1';
const pg = (db: string) => ({ ...process.env, PGHOST: process.env.LM_PG_HOST || '/var/tmp/lmpg', PGPORT: process.env.LM_PG_PORT || '55432', PGUSER: 'postgres', PGDATABASE: db, PGSSLMODE: 'disable' });
const run = (cmd: string, args: string[], db: string) => execFileSync(cmd, args, { env: pg(db), encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });

describe('model from real pg_dump equals information_schema', { skip: !enabled && 'set LM_PG_ROLES_TEST=1 with the local cluster' }, () => {
  const db = `lm_cols_${process.pid}`;
  it('matches for serial, identity, generated, defaults, NOT NULL and later ALTERs', () => {
    run('psql', ['-X', '-q', '-d', 'postgres', '-c', `create database ${db}`], 'postgres');
    try {
      run('psql', ['-X', '-q', '-v', 'ON_ERROR_STOP=1', '-c', PROD_LIKE.replace(/public\.ca_id_seq/, 'public.ca_seq') +
        `create table public.kinds (s serial primary key, bi bigint generated always as identity, gd int generated by default as identity,
           g text generated always as ('x' || s::text) stored, d date default current_date not null, n numeric(10,2), arr text[], "Mixed Case" text);
         alter table public.kinds alter column n set not null; alter table public.kinds add column late jsonb default '{}'::jsonb;`], db);
      const dump = run('pg_dump', ['--schema-only', '--schema=public', db], db);
      const fromDump = modelFromSql(dump);
      const tables = [...fromDump.keys()].sort();
      const fromCatalog = modelFromCatalog(run('psql', ['-X', '-At', '-c', CATALOG_QUERY(tables)], db).split('\n').filter(Boolean));
      assert.deepEqual([...fromCatalog.keys()].sort(), tables);
      for (const t of tables) {
        const flags = (m: TableModel) => cols(m, t).map((c) => `${c.name}:${c.notNull}/${c.hasDefault || c.identity}/${c.generatedAlways && !c.identity}`).sort();
        assert.deepEqual(flags(fromDump), flags(fromCatalog), t);
      }
      assert.deepEqual(checkSeed(fromDump, seedInserts(seed)), []);
    } finally {
      run('psql', ['-X', '-q', '-d', 'postgres', '-c', `drop database ${db}`], 'postgres');
    }
  });
});
