/**
 * Country calling codes (ITU-T E.164) for the phone-number picker.
 * [ISO 3166-1 alpha-2, name, calling code]. Countries that share a code
 * (+1 NANP, +7, +44, +61, +262, +290, +358, +590, +599) are listed
 * separately so customers find their own country; the stored number is the
 * same either way.
 */
export type DialCountry = { iso: string; name: string; dial: string };

const RAW: Array<[string, string, string]> = [
  ['ID', 'Indonesia', '62'],
  ['MY', 'Malaysia', '60'],
  ['SG', 'Singapura', '65'],
  ['BN', 'Brunei Darussalam', '673'],
  ['TL', 'Timor Leste', '670'],
  ['TH', 'Thailand', '66'],
  ['PH', 'Filipina', '63'],
  ['VN', 'Vietnam', '84'],
  ['KH', 'Kamboja', '855'],
  ['LA', 'Laos', '856'],
  ['MM', 'Myanmar', '95'],
  ['AU', 'Australia', '61'],
  ['SA', 'Arab Saudi', '966'],
  ['AE', 'Uni Emirat Arab', '971'],
  ['JP', 'Jepang', '81'],
  ['KR', 'Korea Selatan', '82'],
  ['CN', 'Tiongkok', '86'],
  ['HK', 'Hong Kong', '852'],
  ['TW', 'Taiwan', '886'],
  ['IN', 'India', '91'],
  ['US', 'Amerika Serikat', '1'],
  ['GB', 'Inggris (Britania Raya)', '44'],
  ['NL', 'Belanda', '31'],
  ['DE', 'Jerman', '49'],
  // everything else (sorted by name below)
  ['AF', 'Afganistan', '93'],
  ['ZA', 'Afrika Selatan', '27'],
  ['AL', 'Albania', '355'],
  ['DZ', 'Aljazair', '213'],
  ['AD', 'Andorra', '376'],
  ['AO', 'Angola', '244'],
  ['AI', 'Anguilla', '1'],
  ['AG', 'Antigua dan Barbuda', '1'],
  ['AR', 'Argentina', '54'],
  ['AM', 'Armenia', '374'],
  ['AW', 'Aruba', '297'],
  ['AT', 'Austria', '43'],
  ['AZ', 'Azerbaijan', '994'],
  ['BS', 'Bahama', '1'],
  ['BH', 'Bahrain', '973'],
  ['BD', 'Bangladesh', '880'],
  ['BB', 'Barbados', '1'],
  ['BY', 'Belarus', '375'],
  ['BE', 'Belgia', '32'],
  ['BZ', 'Belize', '501'],
  ['BJ', 'Benin', '229'],
  ['BM', 'Bermuda', '1'],
  ['BT', 'Bhutan', '975'],
  ['BO', 'Bolivia', '591'],
  ['BA', 'Bosnia dan Herzegovina', '387'],
  ['BW', 'Botswana', '267'],
  ['BR', 'Brasil', '55'],
  ['BG', 'Bulgaria', '359'],
  ['BF', 'Burkina Faso', '226'],
  ['BI', 'Burundi', '257'],
  ['TD', 'Chad', '235'],
  ['CL', 'Cile', '56'],
  ['DK', 'Denmark', '45'],
  ['DJ', 'Djibouti', '253'],
  ['DM', 'Dominika', '1'],
  ['EC', 'Ekuador', '593'],
  ['SV', 'El Salvador', '503'],
  ['ER', 'Eritrea', '291'],
  ['EE', 'Estonia', '372'],
  ['SZ', 'Eswatini', '268'],
  ['ET', 'Etiopia', '251'],
  ['FJ', 'Fiji', '679'],
  ['FI', 'Finlandia', '358'],
  ['GA', 'Gabon', '241'],
  ['GM', 'Gambia', '220'],
  ['GE', 'Georgia', '995'],
  ['GH', 'Ghana', '233'],
  ['GI', 'Gibraltar', '350'],
  ['GD', 'Grenada', '1'],
  ['GL', 'Greenland', '299'],
  ['GP', 'Guadeloupe', '590'],
  ['GU', 'Guam', '1'],
  ['GT', 'Guatemala', '502'],
  ['GN', 'Guinea', '224'],
  ['GQ', 'Guinea Khatulistiwa', '240'],
  ['GW', 'Guinea-Bissau', '245'],
  ['GY', 'Guyana', '592'],
  ['GF', 'Guyana Prancis', '594'],
  ['HT', 'Haiti', '509'],
  ['HN', 'Honduras', '504'],
  ['HU', 'Hongaria', '36'],
  ['IQ', 'Irak', '964'],
  ['IR', 'Iran', '98'],
  ['IE', 'Irlandia', '353'],
  ['IS', 'Islandia', '354'],
  ['IL', 'Israel', '972'],
  ['IT', 'Italia', '39'],
  ['JM', 'Jamaika', '1'],
  ['JO', 'Yordania', '962'],
  ['KY', 'Kepulauan Cayman', '1'],
  ['CK', 'Kepulauan Cook', '682'],
  ['FK', 'Kepulauan Falkland', '500'],
  ['FO', 'Kepulauan Faroe', '298'],
  ['MH', 'Kepulauan Marshall', '692'],
  ['MP', 'Kepulauan Mariana Utara', '1'],
  ['SB', 'Kepulauan Solomon', '677'],
  ['TC', 'Kepulauan Turks dan Caicos', '1'],
  ['VG', 'Kepulauan Virgin Britania Raya', '1'],
  ['VI', 'Kepulauan Virgin Amerika Serikat', '1'],
  ['CM', 'Kamerun', '237'],
  ['CA', 'Kanada', '1'],
  ['KZ', 'Kazakhstan', '7'],
  ['KE', 'Kenya', '254'],
  ['KG', 'Kirgizstan', '996'],
  ['KI', 'Kiribati', '686'],
  ['CO', 'Kolombia', '57'],
  ['KP', 'Korea Utara', '850'],
  ['KM', 'Komoro', '269'],
  ['CG', 'Kongo', '242'],
  ['CD', 'Kongo (Republik Demokratik)', '243'],
  ['XK', 'Kosovo', '383'],
  ['CR', 'Kosta Rika', '506'],
  ['HR', 'Kroasia', '385'],
  ['CU', 'Kuba', '53'],
  ['CW', 'Curaçao', '599'],
  ['KW', 'Kuwait', '965'],
  ['LV', 'Latvia', '371'],
  ['LB', 'Lebanon', '961'],
  ['LS', 'Lesotho', '266'],
  ['LR', 'Liberia', '231'],
  ['LY', 'Libya', '218'],
  ['LI', 'Liechtenstein', '423'],
  ['LT', 'Lituania', '370'],
  ['LU', 'Luksemburg', '352'],
  ['MO', 'Makau', '853'],
  ['MK', 'Makedonia Utara', '389'],
  ['MG', 'Madagaskar', '261'],
  ['MW', 'Malawi', '265'],
  ['MV', 'Maladewa', '960'],
  ['ML', 'Mali', '223'],
  ['MT', 'Malta', '356'],
  ['MA', 'Maroko', '212'],
  ['MQ', 'Martinik', '596'],
  ['MR', 'Mauritania', '222'],
  ['MU', 'Mauritius', '230'],
  ['YT', 'Mayotte', '262'],
  ['MX', 'Meksiko', '52'],
  ['EG', 'Mesir', '20'],
  ['FM', 'Mikronesia', '691'],
  ['MD', 'Moldova', '373'],
  ['MC', 'Monako', '377'],
  ['MN', 'Mongolia', '976'],
  ['ME', 'Montenegro', '382'],
  ['MS', 'Montserrat', '1'],
  ['MZ', 'Mozambik', '258'],
  ['NA', 'Namibia', '264'],
  ['NR', 'Nauru', '674'],
  ['NP', 'Nepal', '977'],
  ['NE', 'Niger', '227'],
  ['NG', 'Nigeria', '234'],
  ['NI', 'Nikaragua', '505'],
  ['NU', 'Niue', '683'],
  ['NO', 'Norwegia', '47'],
  ['NC', 'Kaledonia Baru', '687'],
  ['NZ', 'Selandia Baru', '64'],
  ['OM', 'Oman', '968'],
  ['PK', 'Pakistan', '92'],
  ['PW', 'Palau', '680'],
  ['PS', 'Palestina', '970'],
  ['PA', 'Panama', '507'],
  ['CI', 'Pantai Gading', '225'],
  ['PG', 'Papua Nugini', '675'],
  ['PY', 'Paraguay', '595'],
  ['PE', 'Peru', '51'],
  ['PL', 'Polandia', '48'],
  ['PF', 'Polinesia Prancis', '689'],
  ['PT', 'Portugal', '351'],
  ['FR', 'Prancis', '33'],
  ['PR', 'Puerto Riko', '1'],
  ['QA', 'Qatar', '974'],
  ['RE', 'Réunion', '262'],
  ['CZ', 'Republik Ceko', '420'],
  ['CF', 'Republik Afrika Tengah', '236'],
  ['DO', 'Republik Dominika', '1'],
  ['RO', 'Rumania', '40'],
  ['RU', 'Rusia', '7'],
  ['RW', 'Rwanda', '250'],
  ['KN', 'Saint Kitts dan Nevis', '1'],
  ['LC', 'Saint Lucia', '1'],
  ['VC', 'Saint Vincent dan Grenadine', '1'],
  ['PM', 'Saint Pierre dan Miquelon', '508'],
  ['WS', 'Samoa', '685'],
  ['AS', 'Samoa Amerika', '1'],
  ['SM', 'San Marino', '378'],
  ['ST', 'Sao Tome dan Principe', '239'],
  ['SN', 'Senegal', '221'],
  ['RS', 'Serbia', '381'],
  ['SC', 'Seychelles', '248'],
  ['SL', 'Sierra Leone', '232'],
  ['SX', 'Sint Maarten', '1'],
  ['CY', 'Siprus', '357'],
  ['SK', 'Slowakia', '421'],
  ['SI', 'Slovenia', '386'],
  ['SO', 'Somalia', '252'],
  ['ES', 'Spanyol', '34'],
  ['LK', 'Sri Lanka', '94'],
  ['SD', 'Sudan', '249'],
  ['SS', 'Sudan Selatan', '211'],
  ['SR', 'Suriname', '597'],
  ['SE', 'Swedia', '46'],
  ['CH', 'Swiss', '41'],
  ['SY', 'Suriah', '963'],
  ['TJ', 'Tajikistan', '992'],
  ['CV', 'Tanjung Verde', '238'],
  ['TZ', 'Tanzania', '255'],
  ['TG', 'Togo', '228'],
  ['TK', 'Tokelau', '690'],
  ['TO', 'Tonga', '676'],
  ['TT', 'Trinidad dan Tobago', '1'],
  ['TN', 'Tunisia', '216'],
  ['TR', 'Turki', '90'],
  ['TM', 'Turkmenistan', '993'],
  ['TV', 'Tuvalu', '688'],
  ['UG', 'Uganda', '256'],
  ['UA', 'Ukraina', '380'],
  ['UY', 'Uruguay', '598'],
  ['UZ', 'Uzbekistan', '998'],
  ['VU', 'Vanuatu', '678'],
  ['VA', 'Vatikan', '39'],
  ['VE', 'Venezuela', '58'],
  ['WF', 'Wallis dan Futuna', '681'],
  ['YE', 'Yaman', '967'],
  ['GR', 'Yunani', '30'],
  ['ZM', 'Zambia', '260'],
  ['ZW', 'Zimbabwe', '263']
];

/** Indonesia and the most common countries first, then the rest A–Z. */
const PRIORITY = 24;
export const DIAL_COUNTRIES: DialCountry[] = [
  ...RAW.slice(0, PRIORITY),
  ...RAW.slice(PRIORITY).sort((a, b) => a[1].localeCompare(b[1], 'id'))
].map(([iso, name, dial]) => ({ iso, name, dial }));

/** 🇮🇩 from "ID" (regional indicator symbols). */
export const flagOf = (iso: string) =>
  String(iso || '')
    .toUpperCase()
    .replace(/[A-Z]/g, (c) => String.fromCodePoint(0x1f1e6 + c.charCodeAt(0) - 65));

/**
 * Full number from the picker: Indonesia keeps what was typed (08…/8…, the
 * app's usual form); other countries become +<code><number> with the
 * national trunk 0 dropped (except Italy/Vatican, where 0 is part of the number).
 */
export const composePhone = (dial: string, national: string): string => {
  const typed = String(national || '').trim();
  if (!typed) return '';
  if (typed.startsWith('+')) return typed; // already international
  let digits = typed.replace(/\D/g, '');
  if (!digits) return '';
  if (dial === '62') return digits.startsWith('62') ? digits : digits.startsWith('0') ? digits : '0' + digits;
  if (digits.startsWith(dial) && digits.length > dial.length + 6) return '+' + digits; // typed with its code
  if (dial !== '39' && digits.startsWith('0')) digits = digits.slice(1);
  return `+${dial}${digits}`;
};
